using System.Text.Json.Serialization;

namespace SVDSystem.Infrastructure.Dtos;

/// <summary>
/// Response payload returned by the Ollama <c>/api/chat</c> endpoint.
/// </summary>
internal sealed class OllamaChatResponse
{
    /// <summary>
    /// The assistant message generated by the model.
    /// </summary>
    [JsonPropertyName("message")]
    public OllamaMessage? Message { get; set; }
}
